notes: test
tags:
  - facenet
  - online pairs

EPOCHS: 10
PATIENCE: 3
BATCH_SIZE: 16

MODEL_DIR: models/facenet_tune/
RANDOM_SEED: 39
WEIGHT_DECAY: 0.01
LR_WARMUP: 10
CLIP_GRAD_NORM: 5.0
PRETRAINED_MODEL: vggface2
IMG_SIZE : 160
PIN_MEMORY: True

log_interval: 10
learning_rate: 0.003
margin: 1.0
n_samples: 4 # the classes in a mini batch

train_dir: data/facenet_vn_cropped
test_dir: data/facenet_vn_cropped_test