notes: test
tags:
  - facenet
  - online pairs

EPOCHS: 500
PATIENCE: 500
BATCH_SIZE: 256

MODEL_DIR: models/facenet_tune/
RANDOM_SEED: 39
LR_WARMUP: 10
PRETRAINED_MODEL: vggface2
IMG_SIZE : 160
PIN_MEMORY: True

WEIGHT_DECAY: Null
CLIP_GRAD_NORM: Null

log_interval: 10
learning_rate: 0.05
margin: 0.2 # 0.2 in the paper
n_samples: 4 # the classes in a mini batch

train_dir: data/facenet_vn_cropped
test_dir: data/facenet_vn_cropped_test