notes: test
tags:
  - facenet
  - online pairs
  - Augmentation light

EPOCHS: 20
PATIENCE: 5
BATCH_SIZE: 256 # Larger is better

MODEL_DIR: models/facenet_tune/
RANDOM_SEED: 39
LR_WARMUP: 10
PRETRAINED_MODEL: vggface2
IMG_SIZE : 160
PIN_MEMORY: True

WEIGHT_DECAY: Null
CLIP_GRAD_NORM: Null

log_interval: 10
learning_rate: 0.00003 # Must be small
margin: 0.2 # 0.2 in the paper
n_samples: 8 # the classes in a mini batch

train_dir: data/facenet_vn_cropped
test_dir: data/facenet_vn_cropped_test